config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root 'home#index'
  get "up" => "rails/health#show", as: :rails_health_check
  get 'home/addfriend'
  get 'home/friendlist'
  get 'home/acceptfriend'
  get 'home/deletefriend'
  get 'home/timeline'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def addfriend
    commit = params[:commit]
    if commit == "Search"
      @friend_search_result = "";
      search = params[:email]
      if search.to_s.empty?
        puts ""
      elsif search.to_s == current_user.email
        @friend_search_result = "Requesting Yourself ?"
      else 
        query = ActiveRecord::Base.connection.execute("SELECT * FROM users WHERE email=\'" + search + "\'");
        if query.size() > 0   # User Exists
          query = ActiveRecord::Base.connection.execute("SELECT * FROM friendlists WHERE user1=\'" + current_user.email + "\' AND user2=\'" + search + "\'");
          puts query.to_s
          if query.size() > 0 # Already sent request
            if(query.first()["state"] == 2)
              @friend_search_result = "Already a Friend"
            else 
              @friend_search_result = "Already Sent Request to this User"
            end
          else
            query = ActiveRecord::Base.connection.execute("SELECT * FROM friendlists WHERE user2=\'" + current_user.email + "\' AND user1=\'" + search + "\'");
            if query.size() > 0 # Already received request
              if(query.first()["state"] == 2)
                @friend_search_result = "Already a Friend"
              else 
                @friend_search_result = "Already Received Request from this User"
              end
            else
              @friend_search_result = search;
            end
          end
        else
          @friend_search_result = "No such User"
        end
      end
    elsif commit == "Add" 
      sender = current_user.email
      receiver = params[:email]
      query = ActiveRecord::Base.connection.execute("SELECT friendlists.user1 FROM friendlists")
      exist = false
      query.each do |element|
        if element.first().second() == search
          @friend_search_result = search
          break
        end
      end
      if !exist
        time = Time.now
        curtime = time.strftime("%Y-%m-%d %H:%M:%S").to_s;
        query = "INSERT INTO friendlists(user1, user2, state, created_at, updated_at) VALUES(\'"+sender.to_s+"\',\'"+receiver.to_s+"\',1,\'" + curtime + "\',\'" + curtime + "\')"
        ActiveRecord::Base.connection.execute(query)
      end
      redirect_to "/home/addfriend"
    else
      @friend_search_result = "";
    end
  end

  def acceptfriend
    commit = params[:commit]
    sender = params[:email]
    if commit == "Accept"
      time = Time.now
      curtime = time.strftime("%Y-%m-%d %H:%M:%S").to_s;
      query = "UPDATE friendlists SET state=2, updated_at=\'" + curtime + "\' WHERE user2=\'" + current_user.email + "\' AND user1 = \'" + sender.to_s + "\'"
      ActiveRecord::Base.connection.execute(query);
    elsif commit == "Reject"
      sender = params[:email]
      query = "DELETE FROM friendlists WHERE user2=\'" + current_user.email + "\' AND user1 = \'" + sender.to_s + "\'"
      ActiveRecord::Base.connection.execute(query);
    end
  end

  def deletefriend
    sender = params[:email]
    query = "DELETE FROM friendlists WHERE user2=\'" + current_user.email + "\' AND user1 = \'" + sender.to_s + "\'"
    ActiveRecord::Base.connection.execute(query);
    query = "DELETE FROM friendlists WHERE user1=\'" + current_user.email + "\' AND user2 = \'" + sender.to_s + "\'"
    ActiveRecord::Base.connection.execute(query);
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:email, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Kaju App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
	          <%= link_to "Timeline", home_timeline_path, class:"nav-link" %>
	        </li>
	        <li class="nav-item">
	          <%= link_to "My Posts", posts_path, class:"nav-link" %>
	        </li>
	        <li class="nav-item">
	          <%= link_to "Friend List", home_friendlist_path, class:"nav-link" %>
	        </li>
          <li class="nav-item">
	          <%= link_to "Add Friend", home_addfriend_path, class:"nav-link" %>
	        </li>
	        <li class="nav-item">
	          <%= link_to "Edit Password", edit_user_registration_path, class:"nav-link" %>
	        </li>
	        <li class="nav-item">
	          <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class:"nav-link" %>
	        </li>
	      <% else %>
	        <li class="nav-item">
	          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
	        </li>
	        <li class="nav-item">
	          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
	        </li>
	      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/addfriend.html.erb
<h1> Search Friend </h1>

</br>

<%= form_with url: "/home/addfriend", method: :get do |form| %>
  <div class="field mb-3">
    <%= form.text_field :email, class: "form-control", placeholder: "name@example" %>
    </br>
    <%= form.submit "Search", class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

</br> </br>

<% if @friend_search_result.to_s.include?("@") %>
  <%= form_with url: "/home/addfriend", method: :get do |form| %>
    <div class="field mb-3">
      <%= form.text_field :email, :readonly => true, class: "form-control", value:@friend_search_result%>
      </br>
      <%= form.submit "Add", class: "btn btn-primary btn-sm btn-success" %>
    </div>
  <% end %>
<% else %>
  <font color="red"> <%= @friend_search_result %> </font>
<% end %>

</br></br></br></br>

<h1> Sent Requests </h1>
</br></br>
<% query = "SELECT * FROM friendlists WHERE user1=\'" + current_user.email + "\'" %>
<% result = ActiveRecord::Base.connection.execute(query) %>
<% result.each do |element| %>
  <% if element["state"] == 1 %>
    <%= form_with url: "/home/deletefriend", method: :get do |form| %>
      <div class="field mb-3">
        <%= form.text_field :email, :readonly => true, class: "form-control", value:element["user2"] %>
        </br>
        <%= form.submit "Delete", class: "btn btn-primary btn-sm btn-danger" %>
        </br></br></br>
      </div>
    <% end %>
  <% end %> 
<% end %>

app/views/home/friendlist.html.erb
<h1> Friend Requests </h1>
</br></br>
<% query = "SELECT * FROM friendlists WHERE user2=\'" + current_user.email + "\'" %>
<% result = ActiveRecord::Base.connection.execute(query) %>
<% result.each do |element| %>
  <% if element["state"] == 1 %>
    <%= form_with url: "/home/acceptfriend", method: :get do |form| %>
      <div class="field mb-3">
        <%= form.text_field :email, :readonly => true, class: "form-control", value:element["user1"] %>
        </br>
        <%= form.submit "Accept", class: "btn btn-primary btn-sm btn-success" %>
        <%= form.submit "Reject", class: "btn btn-primary btn-sm btn-danger" %>
        </br></br></br>
      </div>
    <% end %>
  <% end %> 
<% end %>

</br></br></br></br>

<h1> Friend List </h1>
</br></br>
<% query = "SELECT * FROM friendlists WHERE user1=\'" + current_user.email + "\'" %>
<% result = ActiveRecord::Base.connection.execute(query) %>
<% result.each do |element| %>
  <% if element["state"] == 2 %>
    <%= form_with url: "/home/deletefriend", method: :get do |form| %>
      <div class="field mb-3">
        <%= form.text_field :email, :readonly => true, class: "form-control", value:element["user2"] %>
        </br>
        <%= form.submit "Delete", class: "btn btn-primary btn-sm btn-danger" %>
        </br></br></br>
      </div>
    <% end %>
  <% end %> 
<% end %>
<% query = "SELECT * FROM friendlists WHERE user2=\'" + current_user.email + "\'" %>
<% result = ActiveRecord::Base.connection.execute(query) %>
<% result.each do |element| %>
  <% if element["state"] == 2 %>
    <%= form_with url: "/home/deletefriend", method: :get do |form| %>
      <div class="field mb-3">
        <%= form.text_field :email, :readonly => true, class: "form-control", value:element["user1"] %>
        </br>
        <%= form.submit "Delete", class: "btn btn-primary btn-sm btn-danger" %>
        </br></br></br>
      </div>
    <% end %>
  <% end %> 
<% end %>

app/views/home/index.html.erb
<h1> Hello 
<% if user_signed_in? %> 
	<%= current_user.email.split('@').first().capitalize() %> 
<% else %>
	Guest
<% end %>
!</h1>

app/views/home/timeline.html.erb
<h1> Timeline </h1>
</br></br>
<% query = "SELECT * FROM posts" %>
<% result = ActiveRecord::Base.connection.execute(query) %>
<% friends = Array.new %>
<% query = "SELECT * FROM friendlists WHERE user1=\'" + current_user.email + "\' AND state=2" %>
<% friends1 = ActiveRecord::Base.connection.execute(query) %>
<% friends1.each do |f1| %>
  <% friends.push(f1["user2"]) %>
<% end %>
<% query = "SELECT * FROM friendlists WHERE user2=\'" + current_user.email + "\' AND state=2" %>
<% friends2 = ActiveRecord::Base.connection.execute(query) %>
<% friends2.each do |f1| %>
  <% friends.push(f1["user1"]) %>
<% end %>
<% result.each do |element| %>
  <% if friends.include?(element["email"]) %>
    <div class="card border-secondary mb-3">
      <div class="card-header"><strong><%= element["email"] %></strong></div>
      <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted"><%= element["created_at"].to_s %></h6></br>
        <p class="card-text"><%= element["content"] %></p>
        <p> <% link_to "Show More", "/posts/"+ element["id"].to_s %> </p>
      </div>
    </div>
    </br></br>
  <% end %>
<% end %>

app/views/layouts/_alerts.html.erb
</br>
<div class="alert alert-info" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kaju App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class = "container"> 
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <br/> 
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  </br> </br>
  <div class="field mb-3">
    <%= form.text_field :email, :readonly => true, value: current_user.email.to_s, class: "form-control" %>
  </div>

  <div>
    <%= form.text_area :content, :rows => "6", class: "form-control"%>
  </div>

  </br> </br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<% if post.email.to_s == current_user.email.to_s %>
  <div class="card border-secondary mb-3" >
    <div class="card-header"><%= post.created_at.to_s %></div>
    <div class="card-body">
      <h6 class="card-subtitle mb-2 text-muted"><% post.created_at.to_s %></h6>
      <p class="card-text"><%= post.content %></p>
      <p> <%= link_to "Options", post, class:"link-info link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover" %> </p>
    </div>
  </div>
  </br></br>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post, class:"link-primary link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover" %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Your Posts</h1>
</br></br>

<div id="posts">
  <% @posts.each do |post| %>
    <% if post.email.to_s == current_user.email.to_s %>
      <%= render post %>
    <% end %>
  <% end %>
</div>

<div class="card text-white bg-success" style="max-width: 7rem;">
  <div class="card-body">
    <h6 class="card-title"><%= link_to "New post", new_post_path, class:"link-light link-offset-2 link-underline-opacity-0" %></h6>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path, class:"link-primary link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover" %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post), class:"link-success link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover" %>
  </br></br>
  <%= button_to "Destroy this post", @post, method: :delete, class: "btn btn-primary btn-sm btn-danger" %>
</div>